name: cadquery
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - ocp=7.7.2
  - pyparsing>=2.1.9
  - sphinx=5.0.1
  - sphinx_rtd_theme
  - black=23.11
  - mypy
  - codecov
  - pytest
  - pytest-cov
  - ezdxf
  - typing_extensions
  - nptyping=2.0.1
  - nlopt
  - path
  - casadi
  - multimethod ==1.9.1
  - pip
  - pip:
    - --editable=.
